### ISSUE TITLE
__ [Bounty]

### ISSUE THREAD

**Issue by faris26877** [ceramicnetwork/.github#249]
### Prize Bounty
[comment]: # List the token type (ETH/ERC-20) and amount.

### Challenge Description
[comment]: # Be as descriptive as possible about what you want to see built. Challenges should be useful for your organization, but open-ended enough to allow for creativity from hackers.

### Submission Requirements
[comment]: # What constitutes a valid submission to win the prize? Would you like a demo included in the submission (Strongly Recommended)?. What will help you determine whether a submission passed a threshold of acceptable quality? Please include any relevant code contribution guidelines/standards, etc.

### Judging Criteria
[comment]: # How will the sponsor ultimately decide the winner/winners from all valid submissions? First valid submission received? Best submission meeting some criteria by the deadline? 

### Winner Announcement Date
[comment]: # Please plan to have judges from your organization (or others you choose) review the submissions as early as possible after the hackathon ends (or immediately upon submission, if you set your submission deadline up to be first-to-submit) to ensure prompt winner announcement and payout.

**Comment by ukstv** [comment]
@faris26877 Would you mind please telling what this is about? Is it by any chance one of those challenges like “create your first issue to learn how to do open source programming”?
